### PR TITLE
The YouTube args are changed, apparently.

### PR DESCRIPTION
**Pull request by SLG**
Also added a catch for the promise, to handle errors in the script better.

### CODE REVIEW

**Comment by gquach** [comment]
I can confirm that this PR fixes the issue with `saveVttFiles();` not working, thank you.

**Review by gquach — APPROVED** [review]

**Comment by benwiley4000** [comment]
I'm so sorry for taking so long to approve. I'll merge this. Can you please confirm @gquach @SLG that the version in master works for you?

**Comment by benwiley4000** [comment]
released in v0.2.0

**Comment by gquach** [comment]
> Can you please confirm @gquach @SLG that the version in master works for you?

Just tried the latest master version, and used the "Simple usage (visiting page in browser)" method and can confirm it works perfectly for me in the latest Chrome browser. Thank you @benwiley4000 and @SLG :)

**Pull request merged**
